# Generated by Django 6.0.5 on 2026-05-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by commas'),
        ),
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
